pipeline {
    agent any

    tools {
        jdk 'Java17'
        maven 'Maven'
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo "Pulling from GITHUB repository"
                git branch: 'main',
                    credentialsId: 'My_cred',
                    url: 'https://github.com/Deekshu966/Devops.git'
            }
        }

        stage('Test the Project') {
            steps {
                echo "Testing my JAVA project"
                bat 'mvn clean test'
            }
            post {
                success {
                    junit '**/target/surefire-reports/*.xml'
                    echo 'Test Run succeeded!'
                }
                failure {
                    echo 'Test Run failed!'
                }
            }
        }

        stage('Build Project') {
            steps {
                echo "Building my JAVA project"
                bat 'mvn clean package -DskipTests'
            }
        }

        stage('Test The Application') {
            steps {
                echo "Application-level testing"
            }
        }

        stage('Deploy the Project') {
            steps {
                echo "Project is getting deployed"
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded '
        }
        failure {
            echo 'Pipeline failed '
        }
    }
}
